import {agentFirstCopy} from './agent-first-copy.mjs'
import {cursorInstallCopy} from './cursor-install-copy.mjs'
export const agentClients=['claude-code','codex','cursor','deepseek','other']
export const clientNames={'claude-code':'Claude Code',codex:'Codex',cursor:'Cursor',deepseek:'DeepSeek Harness',other:'MCP'}
const base='https://github.com/ToTopAI/totop-ai/releases/download/v0.4.1/'
export const clientGuides={
 'claude-code':{native:true,download:base+'totop-ai-claude-code-0.4.1.zip',install:'/plugin marketplace add ToTopAI/totop-ai\n/plugin install totop-ai@totop-ai',manual:'claude mcp add --transport http totop-developer https://api.totop.ai/mcp',connect:'Run /mcp and authorize ToTop in your browser.',upload:'Use authorized local tools and the helper included in the plugin (${CLAUDE_PLUGIN_ROOT}).'},
 codex:{native:true,download:base+'totop-ai-codex-0.4.1.zip',install:'codex plugin marketplace add ToTopAI/totop-ai\ncodex plugin add totop-ai@totop-ai\ncodex mcp login totop-developer',manual:'codex mcp add totop-developer --url https://api.totop.ai/mcp --oauth-client-id codex:totop --oauth-resource https://api.totop.ai/mcp\ncodex mcp login totop-developer',connect:'Desktop: install totop-ai and choose Authenticate. CLI: use mcp login. Keep the existing Codex OAuth configuration.',upload:'Use authorized local execution tools and the contained Node helper; resolve its path relative to the loaded skill.'},
 cursor:{native:true,download:base+'totop-ai-cursor-0.4.1.zip',install:cursorInstallCopy.en.install,manual:'{\n  "mcpServers": {\n    "totop-developer": { "url": "https://api.totop.ai/mcp" }\n  }\n}',connect:'Project config: .cursor/mcp.json. Global config: ~/.cursor/mcp.json. Enable the connection and complete browser OAuth. One-click MCP adds configuration only, not the full plugin.',upload:'Use authorized local tools and the contained helper (${CURSOR_PLUGIN_ROOT}).'},
 deepseek:{native:true,download:base+'totop-ai-0.4.1.tgz',install:'dsh plugin --profile YOUR_PROFILE add ./totop-ai-0.4.1.tgz --save-prod --ignore-scripts',manual:'- id: mcp-totop\n  name: "@deepseek-ai/dsh-mcp-client"\n  config:\n    serverName: totop-developer\n    transport: stdio\n    command: node\n    args: ["/absolute/totop-agent.mjs", "serve", "--profile", "deepseek", "--allow-root", "/absolute/game"]\n    toolCallTimeoutMs: 120000',connect:'Run node /absolute/totop-agent.mjs login --profile deepseek first. Bundle inserts only its own entry; replace the invalid gameDirectory with an explicitly approved directory. Official MCP client pinned to 0.0.1-rc.1.',upload:'The restricted bridge adds prepare_local_artifact and upload_local_artifact. Remove with dsh plugin --profile YOUR_PROFILE remove totop-ai.'},
 other:{native:false,manual:'{\n  "mcpServers": {\n    "totop-developer": { "url": "https://api.totop.ai/mcp" }\n  }\n}',connect:'Prefer native Streamable HTTP + browser OAuth with PKCE and resource=https://api.totop.ai/mcp. Dynamic registration and client metadata documents are supported; do not reuse another client identity.',upload:'Use authorized local tools plus the standalone helper. If remote OAuth or local tools are unavailable, use the stdio example below.'},
}
clientGuides.deepseek.configure='node /absolute/totop-agent.mjs login --profile deepseek\n\n# Merge into YOUR_PROFILE/cordis.patch.yml; do not replace existing entries.\n# Use an explicitly approved game directory (Windows example: C:/Games/my-game).\n- id: totop-ai\n  config:\n    profile: deepseek\n    gameDirectory: /absolute/game'
export const bridgeConfig='{\n  "mcpServers": {\n    "totop-developer": {\n      "command": "node",\n      "args": ["/absolute/totop-agent.mjs", "serve", "--profile", "game-project", "--allow-root", "/absolute/game"]\n    }\n  }\n}'
const keys=['title','intro','connect','upload','install','manual','copy','copied','failed','guide','pending','local','connections','empty','revoke','confirm','refresh','active','revoked','expired','signIn','unavailable','scopes','expires','verified','unverified','promptLead','prompt']
const rows={
 en:'Connect your Agent|Build locally. Connect once. Submit for review and publish after successful deployment.|Connect and authorize|Upload a local game|Install plugin|Manual MCP configuration|Copy|Copied|Copy failed; select the text manually.|Full instructions|Client acceptance pending|Authorized local tools or restricted bridge required|Agent connections|No Agent authorizations yet.|Revoke access|Revoke this Agent authorization?|Refresh|Active|Revoked|Expired|Sign in first|Unavailable. Refresh and retry.|Permissions|Expires|Verified client|Unverified client|Tell your Agent|Read https://totop.ai/mcp.md. Check available tools, OAuth and local-file permissions. Call get_account and get_submission_requirements. Prepare the build and cover using authorized tools or the ToTop bridge. Confirm account, game, version, external services and public intent before submitting. Return a playable link only after approval and successful deployment. Never output credentials.',
 'zh-CN':'连接你的 Agent|在本地制作游戏，连接账号，提交审核；部署成功后公开。|连接并授权|上传本地游戏|安装插件|手动配置 MCP|复制|已复制|复制失败，请手动选择文本。|完整指引|客户端验收待完成|需要获准的本地工具或受限桥接|Agent 授权连接|暂无 Agent 授权。|撤销授权|确定撤销此 Agent 授权？|刷新|有效|已撤销|已过期|请先登录|暂不可用，请刷新重试。|权限|到期时间|已验证客户端|未验证客户端|交给你的 Agent|读取 https://totop.ai/mcp.md，检查可用工具、OAuth 与本地文件权限。调用 get_account 和 get_submission_requirements。使用获准工具或 ToTop 桥接准备构建和封面。提交前确认账号、游戏、版本、外部服务及公开意图；只有审核通过且部署成功后返回可玩链接。不要输出凭据。',
 'zh-TW':'連接你的 Agent|在本機製作遊戲，連接帳號，提交審核；部署成功後公開。|連接並授權|上傳本機遊戲|安裝外掛|手動設定 MCP|複製|已複製|複製失敗，請手動選取文字。|完整指引|客戶端驗收待完成|需要獲准的本機工具或受限橋接|Agent 授權連線|尚無 Agent 授權。|撤銷授權|確定撤銷此 Agent 授權？|重新整理|有效|已撤銷|已過期|請先登入|暫時無法使用，請重新整理。|權限|到期時間|已驗證客戶端|未驗證客戶端|交給你的 Agent|讀取 https://totop.ai/mcp.md，檢查可用工具、OAuth 與本機檔案權限。呼叫 get_account 和 get_submission_requirements。使用獲准工具或 ToTop 橋接準備構建與封面。提交前確認帳號、遊戲、版本、外部服務及公開意圖；審核與部署成功後才回傳遊玩連結。不要輸出憑據。',
 fr:'Connectez votre Agent|Créez localement, connectez votre compte et publiez après validation et déploiement.|Connexion et autorisation|Envoyer un jeu local|Installer le plugin|Configuration MCP manuelle|Copier|Copié|Échec de copie ; sélectionnez le texte.|Guide complet|Validation du client en attente|Outils locaux autorisés ou passerelle restreinte requis|Connexions Agent|Aucune autorisation Agent.|Révoquer|Révoquer cette autorisation Agent ?|Actualiser|Actif|Révoqué|Expiré|Connectez-vous|Indisponible. Actualisez et réessayez.|Permissions|Expiration|Client vérifié|Client non vérifié|Dites à votre Agent|Lisez https://totop.ai/mcp.md. Vérifiez les outils, OAuth et les permissions locales. Appelez get_account et get_submission_requirements. Préparez le jeu avec les outils autorisés ou la passerelle ToTop. Confirmez compte, jeu, version, services externes et publication. Ne renvoyez le lien jouable qu’après validation et déploiement réussi. Ne divulguez aucun identifiant secret.',
 de:'Verbinde deinen Agent|Lokal entwickeln, Konto verbinden und nach Prüfung und erfolgreicher Bereitstellung veröffentlichen.|Verbinden und autorisieren|Lokales Spiel hochladen|Plugin installieren|MCP manuell konfigurieren|Kopieren|Kopiert|Kopieren fehlgeschlagen; Text auswählen.|Vollständige Anleitung|Client-Abnahme ausstehend|Autorisierte lokale Tools oder eingeschränkte Bridge erforderlich|Agent-Verbindungen|Noch keine Agent-Autorisierungen.|Zugriff widerrufen|Diese Agent-Autorisierung widerrufen?|Aktualisieren|Aktiv|Widerrufen|Abgelaufen|Bitte anmelden|Nicht verfügbar. Aktualisieren und erneut versuchen.|Berechtigungen|Ablauf|Verifizierter Client|Nicht verifizierter Client|Sag deinem Agent|Lies https://totop.ai/mcp.md. Prüfe Tools, OAuth und lokale Dateirechte. Rufe get_account und get_submission_requirements auf. Bereite Spiel und Cover mit autorisierten Tools oder der ToTop-Bridge vor. Bestätige Konto, Spiel, Version, externe Dienste und Veröffentlichung. Gib den Spiel-Link erst nach erfolgreicher Prüfung und Bereitstellung zurück. Keine Zugangsdaten ausgeben.',
 es:'Conecta tu Agent|Crea localmente, conecta tu cuenta y publica tras la revisión y el despliegue.|Conectar y autorizar|Subir un juego local|Instalar plugin|Configuración MCP manual|Copiar|Copiado|No se pudo copiar; selecciona el texto.|Guía completa|Validación del cliente pendiente|Se requieren herramientas locales autorizadas o un puente restringido|Conexiones Agent|No hay autorizaciones Agent.|Revocar acceso|¿Revocar esta autorización Agent?|Actualizar|Activo|Revocado|Caducado|Inicia sesión|No disponible. Actualiza y reintenta.|Permisos|Caduca|Cliente verificado|Cliente no verificado|Dile a tu Agent|Lee https://totop.ai/mcp.md. Comprueba herramientas, OAuth y permisos locales. Usa get_account y get_submission_requirements. Prepara el juego y la portada con herramientas autorizadas o el puente ToTop. Confirma cuenta, juego, versión, servicios externos y publicación. Devuelve el enlace solo tras revisión y despliegue correctos. No reveles credenciales.',
 pt:'Conecte seu Agent|Crie localmente, conecte sua conta e publique após revisão e implantação.|Conectar e autorizar|Enviar jogo local|Instalar plugin|Configuração MCP manual|Copiar|Copiado|Falha ao copiar; selecione o texto.|Guia completo|Validação do cliente pendente|Ferramentas locais autorizadas ou ponte restrita necessárias|Conexões Agent|Nenhuma autorização Agent.|Revogar acesso|Revogar esta autorização Agent?|Atualizar|Ativo|Revogado|Expirado|Entre primeiro|Indisponível. Atualize e tente novamente.|Permissões|Expira|Cliente verificado|Cliente não verificado|Diga ao seu Agent|Leia https://totop.ai/mcp.md. Verifique ferramentas, OAuth e permissões locais. Use get_account e get_submission_requirements. Prepare o jogo e a capa com ferramentas autorizadas ou a ponte ToTop. Confirme conta, jogo, versão, serviços externos e publicação. Retorne um link somente após revisão e implantação bem-sucedidas. Não exponha credenciais.',
 it:'Collega il tuo Agent|Crea localmente, collega l’account e pubblica dopo revisione e distribuzione.|Collega e autorizza|Carica un gioco locale|Installa plugin|Configurazione MCP manuale|Copia|Copiato|Copia non riuscita; seleziona il testo.|Guida completa|Verifica del client in attesa|Servono strumenti locali autorizzati o un bridge limitato|Connessioni Agent|Nessuna autorizzazione Agent.|Revoca accesso|Revocare questa autorizzazione Agent?|Aggiorna|Attivo|Revocato|Scaduto|Accedi prima|Non disponibile. Aggiorna e riprova.|Permessi|Scadenza|Client verificato|Client non verificato|Chiedi al tuo Agent|Leggi https://totop.ai/mcp.md. Verifica strumenti, OAuth e permessi locali. Usa get_account e get_submission_requirements. Prepara gioco e copertina con strumenti autorizzati o il bridge ToTop. Conferma account, gioco, versione, servizi esterni e pubblicazione. Restituisci il link solo dopo revisione e distribuzione riuscite. Non mostrare credenziali.',
 ja:'Agent を接続|ローカルで制作し、アカウントを接続。審査とデプロイ成功後に公開。|接続と認証|ローカルゲームをアップロード|プラグインをインストール|MCP を手動設定|コピー|コピー済み|コピー失敗。テキストを選択してください。|詳しい手順|クライアントの検証待ち|許可済みローカルツールまたは制限付きブリッジが必要|Agent 接続|Agent の認証はありません。|認証を取り消す|この Agent の認証を取り消しますか？|更新|有効|取り消し済み|期限切れ|ログインしてください|利用できません。再試行してください。|権限|有効期限|検証済みクライアント|未検証クライアント|Agent に依頼|https://totop.ai/mcp.md を読み、ツール、OAuth とローカル権限を確認。get_account と get_submission_requirements を実行。許可済みツールまたは ToTop ブリッジでゲームと表紙を準備。アカウント、ゲーム、バージョン、外部サービスと公開意図を確認。審査とデプロイ成功後のみプレイリンクを返し、認証情報は表示しない。',
 ko:'Agent 연결|로컬에서 만들고 계정을 연결하세요. 심사와 배포 성공 후 공개됩니다.|연결 및 인증|로컬 게임 업로드|플러그인 설치|MCP 수동 설정|복사|복사됨|복사 실패. 텍스트를 선택하세요.|전체 안내|클라이언트 검증 대기|허용된 로컬 도구 또는 제한된 브리지가 필요합니다|Agent 연결|Agent 인증이 없습니다.|권한 취소|이 Agent 인증을 취소할까요?|새로 고침|활성|취소됨|만료됨|먼저 로그인하세요|사용 불가. 새로 고침 후 재시도하세요.|권한|만료|검증된 클라이언트|미검증 클라이언트|Agent에게 요청|https://totop.ai/mcp.md 를 읽고 도구, OAuth, 로컬 권한을 확인하세요. get_account 와 get_submission_requirements 를 실행하세요. 허용된 도구나 ToTop 브리지로 게임과 표지를 준비하세요. 계정, 게임, 버전, 외부 서비스 및 공개 의도를 확인하세요. 심사와 배포가 성공한 뒤에만 플레이 링크를 반환하고 자격 증명을 노출하지 마세요.',
 ar:'اربط Agent الخاص بك|أنشئ محليًا واربط حسابك وانشر بعد نجاح المراجعة والنشر التقني.|الاتصال والتفويض|رفع لعبة محلية|تثبيت الإضافة|إعداد MCP يدويًا|نسخ|تم النسخ|تعذر النسخ؛ حدد النص يدويًا.|الدليل الكامل|اختبار العميل قيد الانتظار|يلزم أدوات محلية مصرح بها أو جسر مقيد|اتصالات Agent|لا توجد تفويضات Agent.|إلغاء التفويض|هل تريد إلغاء هذا التفويض؟|تحديث|نشط|ملغى|منتهي|سجل الدخول أولًا|غير متاح. حدث وحاول مجددًا.|الصلاحيات|انتهاء الصلاحية|عميل موثق|عميل غير موثق|اطلب من Agent|اقرأ https://totop.ai/mcp.md وتحقق من الأدوات وOAuth وأذونات الملفات. استدع get_account وget_submission_requirements. جهز اللعبة والغلاف بأدوات مصرح بها أو جسر ToTop. أكد الحساب واللعبة والإصدار والخدمات الخارجية ونية النشر. أعد رابط اللعب فقط بعد نجاح المراجعة والنشر. لا تعرض بيانات الاعتماد.',
 vi:'Kết nối Agent|Tạo trên máy, kết nối tài khoản và xuất bản sau khi duyệt và triển khai thành công.|Kết nối và cấp quyền|Tải trò chơi cục bộ|Cài plugin|Cấu hình MCP thủ công|Sao chép|Đã sao chép|Không sao chép được; chọn văn bản.|Hướng dẫn đầy đủ|Chờ kiểm thử ứng dụng|Cần công cụ cục bộ được phép hoặc cầu nối giới hạn|Kết nối Agent|Chưa có quyền Agent.|Thu hồi quyền|Thu hồi quyền Agent này?|Làm mới|Hoạt động|Đã thu hồi|Hết hạn|Đăng nhập trước|Không khả dụng. Làm mới và thử lại.|Quyền|Hết hạn|Ứng dụng đã xác minh|Chưa xác minh|Yêu cầu Agent|Đọc https://totop.ai/mcp.md. Kiểm tra công cụ, OAuth và quyền tệp. Gọi get_account và get_submission_requirements. Chuẩn bị trò chơi và ảnh bìa bằng công cụ được phép hoặc cầu nối ToTop. Xác nhận tài khoản, trò chơi, phiên bản, dịch vụ ngoài và ý định công khai. Chỉ trả liên kết sau khi duyệt và triển khai thành công. Không tiết lộ thông tin xác thực.',
 id:'Hubungkan Agent|Buat secara lokal, hubungkan akun dan terbitkan setelah tinjauan dan penerapan berhasil.|Hubungkan dan otorisasi|Unggah game lokal|Pasang plugin|Konfigurasi MCP manual|Salin|Disalin|Gagal menyalin; pilih teks.|Panduan lengkap|Pengujian klien tertunda|Memerlukan alat lokal berizin atau bridge terbatas|Koneksi Agent|Belum ada otorisasi Agent.|Cabut akses|Cabut otorisasi Agent ini?|Muat ulang|Aktif|Dicabut|Kedaluwarsa|Masuk dahulu|Tidak tersedia. Muat ulang dan coba lagi.|Izin|Kedaluwarsa|Klien terverifikasi|Klien belum terverifikasi|Minta Agent|Baca https://totop.ai/mcp.md. Periksa alat, OAuth dan izin berkas lokal. Panggil get_account dan get_submission_requirements. Siapkan game dan sampul dengan alat berizin atau bridge ToTop. Konfirmasi akun, game, versi, layanan eksternal dan niat publikasi. Kembalikan tautan hanya setelah tinjauan dan penerapan berhasil. Jangan ungkap kredensial.',
 th:'เชื่อมต่อ Agent|สร้างในเครื่อง เชื่อมบัญชี และเผยแพร่หลังตรวจสอบและติดตั้งสำเร็จ|เชื่อมต่อและอนุญาต|อัปโหลดเกมในเครื่อง|ติดตั้งปลั๊กอิน|ตั้งค่า MCP ด้วยตนเอง|คัดลอก|คัดลอกแล้ว|คัดลอกไม่สำเร็จ โปรดเลือกข้อความ|คู่มือฉบับเต็ม|รอทดสอบไคลเอนต์|ต้องใช้เครื่องมือที่อนุญาตหรือบริดจ์แบบจำกัด|การเชื่อมต่อ Agent|ยังไม่มีการอนุญาต Agent|เพิกถอนสิทธิ์|เพิกถอนการอนุญาตนี้หรือไม่?|รีเฟรช|ใช้งาน|เพิกถอนแล้ว|หมดอายุ|เข้าสู่ระบบก่อน|ไม่พร้อมใช้งาน โปรดรีเฟรช|สิทธิ์|วันหมดอายุ|ไคลเอนต์ที่ยืนยันแล้ว|ยังไม่ยืนยันไคลเอนต์|สั่ง Agent|อ่าน https://totop.ai/mcp.md ตรวจสอบเครื่องมือ OAuth และสิทธิ์ไฟล์ เรียก get_account และ get_submission_requirements เตรียมเกมและภาพปกด้วยเครื่องมือที่อนุญาตหรือบริดจ์ ToTop ยืนยันบัญชี เกม รุ่น บริการภายนอก และการเผยแพร่ ส่งลิงก์เล่นเมื่อการตรวจสอบและติดตั้งสำเร็จเท่านั้น ห้ามแสดงข้อมูลรับรอง',
}
export const agentCopy=Object.fromEntries(Object.entries(rows).map(([locale,row])=>{
 const values=row.split('|'),copy=Object.fromEntries(keys.map((k,i)=>[k,values[i]])),first=agentFirstCopy[locale]
 return [locale,{...copy,title:first.title,intro:first.intro,promptLead:first.promptLead,pending:first.pending}]
}))
