const keys=['heading','summary','account','draft','upload','submit','policy','privacy','cancel','allow','untrusted']
const rows={
 en:'Connect to ToTop|This client can manage drafts and submit for review after your confirmation.|Current account|Read games and create or update drafts|Upload game builds and covers|Submit and read review and publication results|Approved games are published after successful deployment. No administrator access or review bypass is granted.|Revoke access anytime in Personal center → Agent connections.|Cancel|Allow connection|Unverified third-party client. The name is self-reported; check its source before authorizing.',
 'zh-CN':'连接 ToTop|此客户端可管理草稿，并在你确认后提交审核。|当前账号|读取游戏并创建、更新草稿|上传游戏构建与封面|提交并查询审核及发布结果|审核通过且部署成功后公开。此授权不包含管理员审批、强制上架或绕过平台审核。|可随时在个人中心的 Agent 接入中撤销。|取消|允许连接|未验证的第三方客户端。名称为自行声明，授权前请确认来源。',
 'zh-TW':'連接 ToTop|此客戶端可管理草稿，並在你確認後提交審核。|目前帳號|讀取遊戲並建立、更新草稿|上傳遊戲構建與封面|提交並查詢審核及發布結果|審核與部署成功後公開。不授予管理員權限或繞過審核能力。|可隨時在個人中心的 Agent 接入撤銷。|取消|允許連接|未驗證的第三方客戶端。名稱為自行聲明，授權前請確認來源。',
 fr:'Connexion à ToTop|Ce client gère les brouillons et soumet après votre confirmation.|Compte actuel|Lire les jeux et gérer les brouillons|Envoyer jeux et couvertures|Soumettre et lire les résultats|Publication après validation et déploiement. Aucun accès administrateur ou contournement.|Révocable dans votre centre personnel → Connexions Agent.|Annuler|Autoriser|Client tiers non vérifié. Nom autodéclaré ; vérifiez sa source.',
 de:'Mit ToTop verbinden|Dieser Client verwaltet Entwürfe und reicht nach deiner Bestätigung ein.|Aktuelles Konto|Spiele lesen und Entwürfe verwalten|Spiele und Cover hochladen|Einreichen und Ergebnisse lesen|Öffentlich nach Prüfung und Bereitstellung. Keine Adminrechte oder Umgehung.|Jederzeit im persönlichen Bereich → Agent-Verbindungen widerrufbar.|Abbrechen|Erlauben|Nicht verifizierter Drittanbieter. Selbst angegebener Name; Quelle prüfen.',
 es:'Conectar con ToTop|Este cliente gestiona borradores y envía tras tu confirmación.|Cuenta actual|Leer juegos y gestionar borradores|Subir juegos y portadas|Enviar y consultar resultados|Público tras revisión y despliegue. Sin acceso administrativo ni evasión.|Revoca en tu centro personal → Conexiones Agent.|Cancelar|Autorizar|Cliente de terceros no verificado. Nombre autodeclarado; comprueba su origen.',
 pt:'Conectar ao ToTop|Este cliente gerencia rascunhos e envia após sua confirmação.|Conta atual|Ler jogos e gerenciar rascunhos|Enviar jogos e capas|Enviar e consultar resultados|Público após revisão e implantação. Sem acesso administrativo ou desvio.|Revogue no centro pessoal → Conexões Agent.|Cancelar|Autorizar|Cliente de terceiros não verificado. Nome autodeclarado; confira a origem.',
 it:'Collega a ToTop|Questo client gestisce bozze e invia dopo la tua conferma.|Account attuale|Leggere giochi e gestire bozze|Caricare giochi e copertine|Inviare e leggere risultati|Pubblico dopo verifica e distribuzione. Nessun accesso amministrativo o aggiramento.|Revoca dal centro personale → Connessioni Agent.|Annulla|Autorizza|Client di terze parti non verificato. Nome autodichiarato; verifica l’origine.',
 ja:'ToTop に接続|このクライアントは下書きを管理し、確認後に審査へ提出します。|現在のアカウント|ゲームを読み、下書きを作成・更新|ゲームと表紙をアップロード|提出と審査・公開結果の確認|審査とデプロイ成功後に公開。管理者権限や審査回避は許可しません。|個人センターの Agent 接続からいつでも取り消せます。|キャンセル|接続を許可|未検証の第三者クライアント。名前は自己申告です。提供元を確認してください。',
 ko:'ToTop 연결|이 클라이언트는 초안을 관리하고 확인 후 심사에 제출합니다.|현재 계정|게임 조회 및 초안 관리|게임과 표지 업로드|제출 및 심사·공개 결과 조회|심사와 배포 성공 후 공개. 관리자 권한이나 심사 우회는 허용되지 않습니다.|개인 센터 → Agent 연결에서 언제든 취소하세요.|취소|연결 허용|미검증 타사 클라이언트. 이름은 자체 신고입니다. 출처를 확인하세요.',
 ar:'الاتصال بـ ToTop|يدير هذا العميل المسودات ويرسلها بعد تأكيدك.|الحساب الحالي|قراءة الألعاب وإدارة المسودات|رفع الألعاب والأغلفة|الإرسال وقراءة النتائج|نشر بعد نجاح المراجعة والتشغيل. دون صلاحيات إدارية أو تجاوز للمراجعة.|ألغ التفويض في المركز الشخصي ← اتصالات Agent.|إلغاء|السماح|عميل خارجي غير موثق. الاسم ذاتي؛ تحقق من مصدره.',
 vi:'Kết nối ToTop|Ứng dụng này quản lý bản nháp và gửi sau khi bạn xác nhận.|Tài khoản hiện tại|Đọc trò chơi và quản lý bản nháp|Tải trò chơi và ảnh bìa|Gửi và đọc kết quả|Công khai sau duyệt và triển khai. Không có quyền quản trị hay bỏ qua duyệt.|Thu hồi tại trung tâm cá nhân → Kết nối Agent.|Hủy|Cho phép|Ứng dụng bên thứ ba chưa xác minh. Tên tự khai báo; kiểm tra nguồn.',
 id:'Hubungkan ke ToTop|Klien ini mengelola draf dan mengirim setelah konfirmasi Anda.|Akun saat ini|Baca game dan kelola draf|Unggah game dan sampul|Kirim dan baca hasil|Publik setelah tinjauan dan penerapan. Tanpa akses admin atau bypass.|Cabut di pusat pribadi → Koneksi Agent.|Batal|Izinkan|Klien pihak ketiga belum terverifikasi. Nama dinyatakan sendiri; periksa sumbernya.',
 th:'เชื่อมต่อ ToTop|ไคลเอนต์จัดการฉบับร่างและส่งหลังคุณยืนยัน|บัญชีปัจจุบัน|อ่านเกมและจัดการฉบับร่าง|อัปโหลดเกมและภาพปก|ส่งและดูผล|เผยแพร่หลังตรวจและติดตั้งสำเร็จ ไม่มีสิทธิ์ผู้ดูแลหรือข้ามตรวจ|เพิกถอนในศูนย์ส่วนตัว → การเชื่อมต่อ Agent|ยกเลิก|อนุญาต|ไคลเอนต์ภายนอกยังไม่ยืนยัน ชื่อที่แจ้งเอง โปรดตรวจแหล่งที่มา',
}
export const consentCopy=Object.fromEntries(Object.entries(rows).map(([locale,row])=>{const values=row.split('|');if(values.length!==keys.length)throw Error('Invalid consent locale');return [locale,Object.fromEntries(keys.map((key,i)=>[key,values[i]]))]}))
