import { createHash } from 'node:crypto'

// Self-contained loopback UI: never interpolate OAuth parameters or load remote assets.
const copy = {
  en: ['Authorization received', 'Return to your Agent to confirm the connection result. You can safely close this tab.', 'Return to your Agent', 'What happens next?', 'Your Agent will finish checking the authorization and report whether the connection succeeded. This page does not confirm a completed connection.', 'Manage Agent connections', 'Authorization could not be completed', 'Return to your Agent and start authorization again. No connection is confirmed by this page.', 'LOCAL AUTHORIZATION', 'Secure browser handoff'],
  fr: ['Autorisation reçue', 'Retournez dans votre Agent pour confirmer la connexion. Vous pouvez fermer cet onglet.', 'Retourner dans votre Agent', 'Et ensuite ?', 'Votre Agent terminera la vérification et indiquera si la connexion a réussi. Cette page ne confirme pas une connexion établie.', 'Gérer les connexions Agent', 'Autorisation non terminée', 'Retournez dans votre Agent et relancez l’autorisation. Cette page ne confirme aucune connexion.', 'AUTORISATION LOCALE', 'Transmission sécurisée'],
  de: ['Autorisierung empfangen', 'Kehren Sie zu Ihrem Agent zurück, um die Verbindung zu bestätigen. Sie können diesen Tab schließen.', 'Zurück zu Ihrem Agent', 'Was passiert als Nächstes?', 'Ihr Agent prüft die Autorisierung und meldet das Verbindungsergebnis. Diese Seite bestätigt keine abgeschlossene Verbindung.', 'Agent-Verbindungen verwalten', 'Autorisierung nicht abgeschlossen', 'Kehren Sie zu Ihrem Agent zurück und starten Sie die Autorisierung erneut. Diese Seite bestätigt keine Verbindung.', 'LOKALE AUTORISIERUNG', 'Sichere Browser-Übergabe'],
  es: ['Autorización recibida', 'Vuelve a tu Agent para confirmar la conexión. Puedes cerrar esta pestaña.', 'Volver a tu Agent', '¿Qué sucede después?', 'Tu Agent verificará la autorización e indicará si la conexión se completó. Esta página no confirma una conexión completa.', 'Gestionar conexiones de Agent', 'Autorización incompleta', 'Vuelve a tu Agent e inicia de nuevo la autorización. Esta página no confirma ninguna conexión.', 'AUTORIZACIÓN LOCAL', 'Transferencia segura'],
  pt: ['Autorização recebida', 'Volte ao seu Agent para confirmar a conexão. Você pode fechar esta aba.', 'Voltar ao seu Agent', 'O que acontece a seguir?', 'Seu Agent verificará a autorização e informará se a conexão foi concluída. Esta página não confirma uma conexão completa.', 'Gerenciar conexões de Agent', 'Autorização não concluída', 'Volte ao seu Agent e inicie a autorização novamente. Esta página não confirma nenhuma conexão.', 'AUTORIZAÇÃO LOCAL', 'Transferência segura'],
  it: ['Autorizzazione ricevuta', 'Torna al tuo Agent per confermare la connessione. Puoi chiudere questa scheda.', 'Torna al tuo Agent', 'Cosa succede ora?', 'Il tuo Agent verificherà l’autorizzazione e comunicherà il risultato. Questa pagina non conferma una connessione completata.', 'Gestisci connessioni Agent', 'Autorizzazione non completata', 'Torna al tuo Agent e avvia nuovamente l’autorizzazione. Questa pagina non conferma alcuna connessione.', 'AUTORIZZAZIONE LOCALE', 'Trasferimento sicuro'],
  ja: ['認証情報を受信しました', 'Agent に戻って接続結果を確認してください。このタブは閉じてもかまいません。', 'Agent に戻ってください', '次のステップ', 'Agent が認証の確認を完了し、接続結果をお知らせします。このページは接続の完了を保証するものではありません。', 'Agent 接続を管理', '認証を完了できませんでした', 'Agent に戻り、認証をやり直してください。このページは接続の完了を確認しません。', 'ローカル認証', '安全なブラウザー連携'],
  ko: ['인증 정보를 받았습니다', 'Agent로 돌아가 연결 결과를 확인하세요. 이 탭을 닫아도 됩니다.', 'Agent로 돌아가기', '다음 단계', 'Agent가 인증을 확인하고 연결 결과를 알려 줍니다. 이 페이지는 연결 완료를 보장하지 않습니다.', 'Agent 연결 관리', '인증을 완료하지 못했습니다', 'Agent로 돌아가 인증을 다시 시작하세요. 이 페이지는 연결 완료를 확인하지 않습니다.', '로컬 인증', '안전한 브라우저 연결'],
  ar: ['تم استلام التفويض', 'ارجع إلى Agent لتأكيد نتيجة الاتصال. يمكنك إغلاق علامة التبويب هذه بأمان.', 'العودة إلى Agent', 'ما الخطوة التالية؟', 'سيتحقق Agent من التفويض ويخبرك بنتيجة الاتصال. لا تؤكد هذه الصفحة اكتمال الاتصال.', 'إدارة اتصالات Agent', 'تعذر إكمال التفويض', 'ارجع إلى Agent وابدأ التفويض مجددًا. لا تؤكد هذه الصفحة أي اتصال.', 'تفويض محلي', 'تسليم آمن عبر المتصفح'],
  vi: ['Đã nhận ủy quyền', 'Quay lại Agent để xác nhận kết quả kết nối. Bạn có thể đóng tab này.', 'Quay lại Agent', 'Tiếp theo là gì?', 'Agent sẽ kiểm tra ủy quyền và báo kết quả kết nối. Trang này không xác nhận kết nối đã hoàn tất.', 'Quản lý kết nối Agent', 'Không thể hoàn tất ủy quyền', 'Quay lại Agent và bắt đầu ủy quyền lại. Trang này không xác nhận kết nối.', 'ỦY QUYỀN CỤC BỘ', 'Chuyển tiếp trình duyệt an toàn'],
  id: ['Otorisasi diterima', 'Kembali ke Agent untuk memastikan hasil koneksi. Anda dapat menutup tab ini.', 'Kembali ke Agent', 'Apa langkah berikutnya?', 'Agent akan memeriksa otorisasi dan melaporkan hasil koneksi. Halaman ini tidak memastikan koneksi telah selesai.', 'Kelola koneksi Agent', 'Otorisasi belum selesai', 'Kembali ke Agent dan mulai otorisasi lagi. Halaman ini tidak memastikan koneksi apa pun.', 'OTORISASI LOKAL', 'Serah terima browser aman'],
  th: ['ได้รับการอนุญาตแล้ว', 'กลับไปที่ Agent เพื่อยืนยันผลการเชื่อมต่อ คุณสามารถปิดแท็บนี้ได้', 'กลับไปที่ Agent', 'ขั้นตอนถัดไปคืออะไร?', 'Agent จะตรวจสอบการอนุญาตและแจ้งผลการเชื่อมต่อ หน้านี้ไม่ได้ยืนยันว่าการเชื่อมต่อเสร็จสมบูรณ์', 'จัดการการเชื่อมต่อ Agent', 'ไม่สามารถดำเนินการอนุญาตให้เสร็จสิ้น', 'กลับไปที่ Agent แล้วเริ่มการอนุญาตใหม่ หน้านี้ไม่ได้ยืนยันการเชื่อมต่อ', 'การอนุญาตในเครื่อง', 'ส่งต่อผ่านเบราว์เซอร์อย่างปลอดภัย'],
  'zh-CN': ['已收到授权', '请返回你的 Agent 确认连接结果。你可以安全地关闭此标签页。', '返回你的 Agent', '接下来会发生什么？', 'Agent 将完成授权校验，并告知连接是否成功。此页面仅表示已收到授权，不代表连接已经完成。', '管理 Agent 连接', '授权未能完成', '请返回你的 Agent，重新发起授权。此页面未确认任何连接成功。', '本地授权', '安全的浏览器授权交接'],
  'zh-TW': ['已收到授權', '請返回你的 Agent 確認連線結果。你可以安全地關閉此分頁。', '返回你的 Agent', '接下來會發生什麼？', 'Agent 將完成授權驗證，並告知連線是否成功。此頁面僅表示已收到授權，不代表連線已經完成。', '管理 Agent 連線', '授權未能完成', '請返回你的 Agent，重新發起授權。此頁面未確認任何連線成功。', '本機授權', '安全的瀏覽器授權交接'],
}
export const callbackLocales = Object.keys(copy)
export function callbackLocale(header = '') {
  const preferences = String(header).split(',').slice(0, 30).map((part, index) => {
    const [tag, ...parameters] = part.trim().split(';')
    const quality = parameters.find(value => value.trim().startsWith('q='))?.trim().slice(2)
    return { tag: tag.toLowerCase(), quality: quality === undefined ? 1 : Number(quality), index }
  }).filter(item => Number.isFinite(item.quality) && item.quality > 0 && item.quality <= 1).sort((a, b) => b.quality - a.quality || a.index - b.index)
  for (const { tag } of preferences) {
    if (/^zh(?:-|$)/.test(tag)) return /^zh-(?:tw|hk|mo|hant)(?:-|$)/.test(tag) ? 'zh-TW' : 'zh-CN'
    const language = tag.split('-')[0]
    if (Object.hasOwn(copy, language)) return language
  }
  return 'en'
}
const css = `
:root{color-scheme:dark;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#f6f5f0;background:#101218}*{box-sizing:border-box}body{margin:0;min-height:100svh;display:grid;place-items:center;padding:32px 20px;background:radial-gradient(ellipse at 50% 5%,#e4bc4c12,transparent 55%),#101218}body:before{content:"";position:fixed;inset:0;pointer-events:none;background-image:linear-gradient(#ffffff03 1px,transparent 1px),linear-gradient(90deg,#ffffff03 1px,transparent 1px);background-size:48px 48px}.shell{position:relative;width:min(100%,560px)}.brand{display:flex;align-items:center;justify-content:center;gap:10px;margin-block-end:30px;font-size:23px;font-weight:800;letter-spacing:-.8px;direction:ltr}.brand svg{width:34px;height:38px}.brand span span{color:#f3ca50}.card{padding:40px;border:1px solid #353640;border-radius:24px;background:linear-gradient(160deg,#1d2029,#171920);box-shadow:0 24px 80px #0005;text-align:center;overflow-wrap:anywhere}.eyebrow{color:#a7aab6;font-size:11px;font-weight:600;letter-spacing:2px;margin:0 0 28px}.status{width:76px;height:76px;margin:0 auto 24px;display:grid;place-items:center;border-radius:24px;background:#efc94f12;border:1px solid #eac14940;color:#f0c84b;box-shadow:0 0 32px #eac1490a}.status svg{width:34px;height:34px}.error .status{color:#efb2a6;border-color:#efb2a640;background:#efb2a60a}h1{font-size:clamp(26px,5vw,32px);line-height:1.3;letter-spacing:-.8px;margin:0 0 16px}.description{font-size:15px;line-height:1.75;color:#afb2bf;margin:0 auto;max-width:390px}.next{display:flex;align-items:center;justify-content:center;gap:10px;margin:28px 0 22px;min-height:52px;padding:12px 16px;border:1px solid #f0c84b38;border-radius:12px;background:#f0c84b0b;color:#f0cd67;font-size:14px;font-weight:600}.next svg{width:18px;height:18px;flex-shrink:0}details{text-align:start;border-block-start:1px solid #333641;padding-block-start:20px;color:#afb2bf;font-size:13px;line-height:1.7}summary{cursor:pointer;color:#d5d6df;min-height:32px}details p{margin:12px 0 0}.manage{display:inline-flex;align-items:center;justify-content:center;min-height:44px;color:#c3c6d1;font-size:13px;text-underline-offset:4px;margin-block-start:20px}.manage:hover{color:#f0cd67}:focus-visible{outline:2px solid #f0c84b;outline-offset:5px;border-radius:4px}.footer{display:flex;align-items:center;justify-content:center;gap:7px;margin:22px 0 0;font-size:12px;color:#8e919f}.footer svg{width:14px;height:14px}.card{animation:appear .35s ease-out}@keyframes appear{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@media(max-width:480px){body{padding:24px 16px}.card{padding:30px 24px;border-radius:20px}.brand{margin-block-end:24px}.eyebrow{letter-spacing:1px}.status{width:68px;height:68px}}@media(prefers-reduced-motion:reduce){.card{animation:none}}`
const script = "try{history.replaceState(null,'',location.pathname)}catch{}"
const hash = value => createHash('sha256').update(value).digest('base64')
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;')
const svg = (content, extra = '') => `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" ${extra}>${content}</svg>`
export function callbackPage({ state = 'received', language = 'en' } = {}) {
  const locale = callbackLocales.includes(language) ? language : 'en', text = copy[locale].map(escape), received = state === 'received'
  return {
    headers: {
      'Content-Type': 'text/html; charset=utf-8', 'Content-Language': locale, 'Cache-Control': 'no-store',
      'Referrer-Policy': 'no-referrer', 'X-Content-Type-Options': 'nosniff',
      'Content-Security-Policy': `default-src 'none'; style-src 'sha256-${hash(css)}'; script-src 'sha256-${hash(script)}'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'`,
    },
    html: `<!doctype html><html lang="${locale}" dir="${locale === 'ar' ? 'rtl' : 'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${text[received ? 0 : 6]} · ToTop</title><style>${css}</style><script>${script}</script></head><body><main class="shell"><div class="brand"><svg aria-hidden="true" viewBox="0 0 34 38"><path fill="#f3ca50" d="M17 0 34 10v19l-8 5V15l-9-5-9 5v19l-8-5V10Z"/><path fill="#dbaa30" d="m17 15 8 5v18l-8-5Z"/><path fill="#ffe07a" d="m17 15-8 5 8 5 8-5Z"/></svg><span>ToTop <span>AI</span></span></div><section class="card${received ? '' : ' error'}" aria-labelledby="title"><p class="eyebrow">${text[8]}</p><div class="status">${svg(received ? '<path d="m5 12 4 4L19 6"/>' : '<path d="M12 5v8m0 4h.01"/>')}</div><h1 id="title">${text[received ? 0 : 6]}</h1><p class="description">${text[received ? 1 : 7]}</p><div class="next">${svg('<path d="M20 12H4m6-6-6 6 6 6"/>')}<span>${text[2]}</span></div><details><summary>${text[3]}</summary><p>${text[4]}</p></details><a class="manage" href="https://creator.totop.ai/agents?lang=${locale}" target="_blank" rel="noopener noreferrer">${text[5]}</a></section><p class="footer">${svg('<rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>')}<span>${text[9]}</span></p></main></body></html>`,
  }
}
